language: node_js

branches:
  only:
    - main

node_js:
  - "12"

install:
  - cd c4-final-project-starter-code/backend  
  - npm install -g serverless@3.32.2
  - npm update --save
  - npm audit fix

script:
  - cd c4-final-project-starter-code/backend
  - serverless deploy

environments:
  - AWS_ACCESS_KEY_ID=${ENV_AWS_ACCESS_KEY}
  - AWS_SECRET_ACCESS_KEY=${ENV_AWS_SECRET_ACCESS}
  - SERVERLESS_ACCESS_KEY=${SERVERLESS_ACCESS_KEY}