language: node_js

branches:
  only:
    - main

node_js:
  - "12"

install:
  - npm install -g serverless
  - travis_retry npm install

script:
  - cd c4-final-project-starter-code\backend
  - serverless deploy

environments:
  - AWS_ACCESS_KEY_ID=${ENV_AWS_ACCESS_KEY}
  - AWS_SECRET_ACCESS_KEY=${ENV_AWS_SECRET_ACCESS}