language: node_js

branches:
  only:
    - main

node_js:
  - "12"

install:
  - cd c4-final-project-starter-code/backend  
  - npm install -g serverless@3.32.2
  - echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID >> ~/.aws/credentials
  - echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY >> ~/.aws/credentials
  - echo AWS_REGION=$AWS_REGION >> ~/.aws/credentials
  - npm update --save
  - npm audit fix

script:
  - serverless deploy

environments:
  # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  # - AWS_SECRET_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
  # - SERVERLESS_ACCESS_KEY=${SERVERLESS_ACCESS_KEY}